//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDevelop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTest
    {
        public int Id { get; set; }
        public string text { get; set; }
        public string answer1 { get; set; }
        public string answer2 { get; set; }
        public string answer3 { get; set; }
        public string answer4 { get; set; }
        public string rightAnswer { get; set; }
        public int trainingId { get; set; }
        public int mark { get; set; }
    
        public virtual Training Training1 { get; set; }
    }
}
