//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDevelop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTraining
    {
        public int userID { get; set; }
        public int trainingID { get; set; }
        public int CompleteCounter { get; set; }
        public Nullable<int> rate { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual User User { get; set; }
    }
}
